### ISSUE TITLE
is line rec.init_recommender(is_static) wrong?

### ISSUE THREAD

**Issue by Sandy4321** [takuti/stream-recommender#2]
I can not run till I changed           
   in  file experiment.py  line 
rec.init_recommender(is_static)
to
            rec.initialize(is_static) 

is it correct to use  rec.initialize(is_static)  ?
thanks

**Comment by takuti** [comment]
Could you provide your FluRS version (installed `pip install flurs` or `pip install .` on source) and error message?

**Comment by Sandy4321** [comment]
I reinstalled FluRS as you told me 
pip install .
when I use pip list 
it is what I get
flurs (0.0.2)
error message is:
File "d:\Recommender systems\code\stream-recommender-master\experiment.py", line 293, in <module>
  cli()
File "C:\Users\Sander\Anaconda3\Lib\site-packages\click\core.py", line 722, in __call__
  return self.main(*args, **kwargs)
File "C:\Users\Sander\Anaconda3\Lib\site-packages\click\core.py", line 697, in main
  rv = self.invoke(ctx)
File "C:\Users\Sander\Anaconda3\Lib\site-packages\click\core.py", line 895, in invoke
  return ctx.invoke(self.callback, **ctx.params)
File "C:\Users\Sander\Anaconda3\Lib\site-packages\click\core.py", line 535, in invoke
  return callback(*args, **kwargs)
File "d:\Recommender systems\code\stream-recommender-master\experiment.py", line 274, in cli
  res = exp.iMF(is_static=True) if model == 'static-MF' else exp.iMF()
File "d:\Recommender systems\code\stream-recommender-master\experiment.py", line 69, in iMF
  model, res = self.__run(create)
File "d:\Recommender systems\code\stream-recommender-master\experiment.py", line 221, in __run
  model = callback()
File "d:\Recommender systems\code\stream-recommender-master\experiment.py", line 66, in create
  rec.init_recommender(is_static)

builtins.AttributeError: 'MFRecommender' object has no attribute 'init_recommender'

**Comment by Sandy4321** [comment]
by the way 
it is message for flurs instalaltions by pip install .
Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

D:\Recommender systems\code\flurs_feb21_for_installation\flurs-master\flurs-master>pip install .
Processing d:\recommender systems\code\flurs_feb21_for_installation\flurs-master\flurs-master
  Requirement already satisfied (use --upgrade to upgrade): flurs==0.0.2 from file:///D:/Recommender%20systems/code/flurs_feb21_for_installation/flurs-master/flurs-master in c:\users\sander\anaconda3\lib\site-packages
Requirement already satisfied: numpy in c:\users\sander\anaconda3\lib\site-packages (from flurs==0.0.2)
Requirement already satisfied: scipy in c:\users\sander\anaconda3\lib\site-packages (from flurs==0.0.2)
Requirement already satisfied: scikit_learn in c:\users\sander\anaconda3\lib\site-packages (from flurs==0.0.2)
Requirement already satisfied: mmh3 in c:\users\sander\anaconda3\lib\site-packages (from flurs==0.0.2)
Building wheels for collected packages: flurs
  Running setup.py bdist_wheel for flurs ... done
  Stored in directory: C:\Users\Sander\AppData\Local\pip\Cache\wheels\e3\22\aa\87668f0da413527d489b49c21a369d1e28d91bfd7a22741256
Successfully built flurs

D:\Recommender systems\code\flurs_feb21_for_installation\flurs-master\flurs-master>

as we can see it is written
  Requirement already satisfied (use --upgrade to upgrade): flurs==0.0.2 from

**Comment by takuti** [comment]
You are actually using the latest version of FluRS (0.0.2), but code in this repo was created with FluRS 0.0.1. See [requirements.txt](https://github.com/takuti/stream-recommender/blob/master/requirements.txt) for full dependency.

Note that this repo is just snapshot of my past experiments and currently unmaintained; if you want to re-use these code with the latest FluRS (0.0.2+), you have to manually modify them for now.

**Comment by Sandy4321** [comment]
I see, thanks for help, by the way may it is good idea to use it with FluRS 0.0.1, may you share zip file with FluRS 0.0.1 , for example by email, my email is sndr.stpnv@gmail.com

**Comment by takuti** [comment]
v0.0.1 is of course accessible on GitHub: https://github.com/takuti/flurs/releases/tag/0.0.1

**Comment by Sandy4321** [comment]
great thanks, but how I can use it? should I uninstall ver 0.0.2 and install version 0.0.1?

**Comment by takuti** [comment]
e.g., https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip
